on:
  workflow_call:
    inputs:
      software-version:
        required: false
        type: string
      platforms:
        required: false
        type: string
        default: linux/amd64
      image-name:
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.ref == '${{ github.event.repository.default_branch }}'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: github.ref == '${{ github.event.repository.default_branch }}'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ inputs.image-name }}
            ghcr.io/${{ inputs.image-name }}
          tags: |
            type=raw,value=${{ inputs.software-version }},enable=${{ inputs.software-version != ''}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
      - name: Build for test
        id: build
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: ${{ inputs.image-name }}:test
          build-args: |
            VERSION=${{ inputs.software-version || github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # TODO: use with github code scanning
      #       https://github.com/aquasecurity/trivy-action#using-trivy-with-github-code-scanning
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        continue-on-error: true
        with:
          image-ref: ${{ steps.build.outputs.imageid }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
      # Push image to docker registries (rebuilds images using cache from previous steps)
      - name: Build and Push
        if: github.ref == '${{ github.event.repository.default_branch }}'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ inputs.software-version || github.sha }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Hub Description
        if: github.ref == '${{ github.event.repository.default_branch }}'
        uses: peter-evans/dockerhub-description@ede0e66c26c29b05c9e12e1d999564171a061c65
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ inputs.image-name }}
