on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at}}
            VCS_REF=${{ github.head_ref }}
          tags: |
            docker.io/guillaumedsde/qbittorrent-distroless:${{ github.sha }}
            docker.io/guillaumedsde/qbittorrent-distroless:latest
          platforms: |
            linux/amd64